ekf_filter_node:
  ros__parameters:

    # ------------------------------
    # General filter settings
    # ------------------------------
    frequency: 50.0                           # Filter update frequency (Hz)
    two_d_mode: false                         # Set 'true' if you really only want to operate in a planar environment
    publish_acceleration: true                # Publish acceleration state
    publish_tf: true                          # Whether to broadcast transform over /tf

    # Frame names
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    print_diagnostics: true


    # ------------------------------
    # ODOMETRY CONFIGURATION
    # ------------------------------
    odom0: /yaw_rate/odom                              # Odometry topic
    odom0_config: [true,  true,  false,       # x, y, z positions
                   false, false, true,        # roll, pitch, yaw angles
                   true,  false, false,       # vx, vy, vz velocities
                   false, false, true,        # roll_rate, pitch_rate, yaw_rate
                   false, false, false]       # ax, ay, az accelerations

    # Typically for an Ackermann platform:
    #   - fuse x, y positions
    #   - skip z position (since it's presumably constant on flat ground)
    #   - do not fuse roll, pitch angles
    #   - fuse yaw angle
    #   - fuse vx (forward velocity)
    #   - skip vy (no lateral velocity in ideal Ackermann)
    #   - skip vz
    #   - fuse yaw rate if it is included in your odometry message

    odom0_differential: false                 # 'false' if your odometry is already in absolute form
    odom0_queue_size: 2
    # odom0_nodelay: false
    odom0_relative: true
    odom0_pose_use_child_frame: false
    # odom0_pose_rejection_threshold: 5         # Pose outlier rejection
    # odom0_twist_rejection_threshold: 1        # Twist outlier rejection

    # ------------------------------
    # FIRST IMU CONFIGURATION
    # ------------------------------
    imu0: /imu_055/data                      # IMU 0 topic
    imu0_config: [false, false, false,        # x, y, z positions
                  true,  true,  true,         # roll, pitch, yaw angles
                  false, false, false,        # vx, vy, vz velocities
                  true,  true,  true,         # roll_rate, pitch_rate, yaw_rate
                  true,  true,  true]         # ax, ay, az accelerations

    imu0_queue_size: 4
    # imu0_nodelay: false
    imu0_remove_gravitational_acceleration: false
    # imu0_pose_rejection_threshold: 0.8
    # imu0_twist_rejection_threshold: 1.0
    # imu0_linear_acceleration_rejection_threshold: 1.0

    # ------------------------------
    # SECOND IMU CONFIGURATION
    # ------------------------------
    imu1: /imu_086/data                      # IMU 1 topic
    imu1_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu1_queue_size: 4
    # imu1_nodelay: false
    imu1_remove_gravitational_acceleration: false
    # imu1_pose_rejection_threshold: 0.8
    # imu1_twist_rejection_threshold: 1.0
    # imu1_linear_acceleration_rejection_threshold: 1.0

    # process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
    #                         0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]

    # [ADVANCED] This represents the initial value for the state estimate error covariance matrix. Setting a diagonal
    # value (variance) to a large value will result in rapid convergence for initial measurements of the variable in
    # question. Users should take care not to use large values for variables that will not be measured directly. The values
    # are ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Defaults to the diagonal values below
    # if unspecified. In this example, we specify only the diagonal of the matrix.
    # initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9]
