slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: /odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05 # Publish transforms at 20 Hz
    map_update_interval: 0.5 # Faster updates for dynamic environments
    resolution: 0.05
    min_laser_range: 0.2 # Minimum range for RPLidar S3
    max_laser_range: 40.0 # Maximum range for RPLidar S3
    minimum_time_interval: 0.2 # Higher frequency updates for faster robots
    transform_timeout: 0.2
    tf_buffer_duration: 10.0 # Shorter buffer for real-time performance
    stack_size_to_use: 40000000
    enable_interactive_mode: false

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.3 # Smaller distance thresholds for finer updates
    minimum_travel_heading: 0.2 # Reduced for better angular response
    scan_buffer_size: 15 # Reasonable for real-time operation
    scan_buffer_maximum_scan_distance: 20.0 # Match scan limits to environment size
    link_match_minimum_response_fine: 0.15
    link_scan_maximum_distance: 2.5
    loop_search_maximum_distance: 6.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.4
    loop_match_minimum_response_fine: 0.5

    # Correlation Parameters
    correlation_search_space_dimension: 0.8
    correlation_search_space_resolution: 0.02
    correlation_search_space_smear_deviation: 0.1

    # Loop Closure Parameters
    loop_search_space_dimension: 10.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.04

    # Scan Matcher Parameters
    distance_variance_penalty: 0.3 # Prioritize smoother trajectories
    angle_variance_penalty: 0.7
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.8
    minimum_distance_penalty: 0.4
    use_response_expansion: true
