# nav2_params.yaml
amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/absolute/path/to/carver_controller/maps/my_map.yaml"
    frame_id: "map"

planner_server:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false
